### ISSUE TITLE
"count" method returns string number with Amazon Aurora.

### ISSUE THREAD

**Issue by watanabejunya** [jarektkaczyk/hookable#12]
Dear jarektkaczyk,

I greatly appreciate your works(hookable, eloquence, etc...), they are so helpful.
But I found one minor issue that the method **"count()"** in "Sofa\Hookable\Builder" returns string number with **Amazon Aurora database**.
It works well with MySQL on the local machine.
I think you should cast the result returned from "aggregate()" as [Eloquent does](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Query/Builder.php#L1958).

```
return (int) $this->aggregate(__FUNCTION__, (array) $columns);
```

Would you consider my suggestion?

Best regards.

**Comment by jarektkaczyk** [comment]
Hey bro,
sorry for late reply - yes, it makes sense. Can you make a PR to `5.4`?
