### ISSUE TITLE
Declaration of Sofa\Hookable\Builder::pluck() should be compatible with Illuminate\Database\Eloquent\Builder::pluck($column, $key = NULL)

### ISSUE THREAD

**Issue by mtdavidson** [jarektkaczyk/hookable#4]
Hi

I'm seeing this error when using the library in Laravel 5.2 

```local.ERROR: exception 'ErrorException' with message 'Declaration of Sofa\Hookable\Builder::pluck() should be compatible with Illuminate\Database\Eloquent\Builder::pluck($column, $key = NULL)' in /PATH/vendor/sofa/hookable/src/Builder.php:13```

the simple solution seems to be to alter the method declaration and add the ```$key = NULL``` as a parameter so that it matches the required signature of Illuminate\Database\Eloquent\Builder.

I can submit a pull request to introduce this change but are you considering 5.2 compatibility at this time? and if so are you wanting to keep 5.1 compatibility?

I'm interested in this for making use of your eloquence package so might need to do some changes to that for 5.2 as well. 

Thanks

Mark

**Comment by jarektkaczyk** [comment]
Hi, it's not just the signature of this method: https://github.com/jarektkaczyk/hookable/pull/3

Stay tuned

**Comment by jarektkaczyk** [comment]
@mtdavidson it's done on https://github.com/jarektkaczyk/hookable/tree/5.2

this is now the default branch, require it as `"sofa/hookable": "~5.2"` and it will work.

**Comment by mtdavidson** [comment]
:+1:
