### ISSUE TITLE
"shared static" causes BadMethodCallException on Builder.

### ISSUE THREAD

**Issue by Blizzke** [jarektkaczyk/hookable#6]
This problem happens while using Eloquence but it seems to be Hookable related, so I'm reporting it here.

I'm running this on PHP 7.0.12.

I have my own base model class where I add the `Eloquence` trait, so I'm not using the provided `Model`.

For the purpose of this I have 2 classes:

`Category` (use `Mappable`) <-- MyModel (use `Eloquence`)
`User` <-- MyModel (use `Eloquence`)

When the Category is booted, it receives the hooks for `Mappable` as it should. 
However, when after that I use the `User` model, I get an error `Call to undefined method Sofa\Eloquence\Query\Builder::hasMapping()` 

While debugging I noticed that `User::setAttribute('first_name', ...` gets a call to `/sofa/eloquence/src/Mappable/Hooks.php:127` in the pipeline. 

Further debugging turned up that the User does indeed have a bound hook to the `Mappable` trait, as if the static defined in the `Hookable` trait is shared between the classes.

Dunno if this is something PHP specific but I was under the impression that statics in a trait resulted in separate instances per class, but this insinuates differently...

The stack trace for your viewing pleasure:

```
3) UserTest::testThatAnOldPasswordIsUpdatedOnLogin
BadMethodCallException: Call to undefined method Sofa\Eloquence\Query\Builder::hasMapping()

/app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2450
/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1454
/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:3524
/app/vendor/sofa/eloquence/src/Mappable/Hooks.php:127
/app/vendor/sofa/hookable/src/Pipeline.php:84
/app/vendor/sofa/hookable/src/Pipeline.php:88
/app/vendor/sofa/hookable/src/Hookable.php:245
/app/vendor/sofa/hookable/src/Hookable.php:114
/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:443
/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:281
/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:168
/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:2280
/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:170
/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:139
/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:113
/app/tests/unit/packages/users/UserTest.php:24
```

**Comment by jarektkaczyk** [comment]
That's true, if you use base model, then `static` context will be shared, which makes things kinda break.
